apiVersion: apps/v1
kind: Deployment

metadata:
  name: zerotouch-app
  namespace: zerotouch

spec:
  replicas: 1

  selector:
    matchLabels:
      app: zerotouch

  template:
    metadata:
      labels:
        app: zerotouch

    spec:
      containers:
        - name: zerotouch
          image: zerotouch:latest
          imagePullPolicy: Never

          envFrom:
            - configMapRef:
                name: zerotouch-config

            - secretRef:
                name: zerotouch-secret

          ports:
            - containerPort: 8000