apiVersion: v1
kind: Secret

metadata:
  name: zerotouch-secret
  namespace: zerotouch

type: Opaque

stringData:
  DATABASE_USER: {{ .Values.secret.DATABASE_USER }}
  DATABASE_PASSWORD: {{ .Values.secret.DATABASE_PASSWORD }}